### ISSUE TITLE
Does not compile with Crystal 0.23

### ISSUE THREAD

**Issue by veelenga** [drujensen/kemalyst-validators#2]
The error:

```cr
in spec/kemalyst-validators_spec.cr:7: undefined method 'validate'

  validate :name, "is required", -> (this : Person) { this.name != nil }
  ^~~~~~~~
```

Could you please suggest how to fix this properly?

UPDATE: [refs #4639](https://github.com/crystal-lang/crystal/issues/4639)
